config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :users, only: [:create]
      resources :places, only: [:index]
    end
  end

  get 'sign_in', to: 'authentication#sign_in'
  get 'sign_out', to: 'authentication#sign_out'

  resources :locations, only: [:index, :show]

  root 'home#index'
end

app/models/here/place.rb
module Here
  class Place
    include Her::Model
    use_api PLACES_API
    collection_path 'places/v1/discover/search?'

    FOOD_CATEGORY = %w(restaurant snacks-fast-food coffee-tea kiosk-convenience-store)
    
    def self.search(params)
      query = { 
        at: "#{params[:latitude]},#{params[:longitude]}",
        q: params[:keyword],
        accept: 'application/json',
        app_id: ENV['HERE_MAP_APP_ID'],
        app_code: ENV['HERE_MAP_APP_CODE']
      }.to_param

      self.get("#{collection_path}#{query}")
    end

    def self.search_with_wrap_to_model(params)
      response = self.search(params)
      collection = response.results[:items].map {|item| FOOD_CATEGORY.include?(item[:category][:id]) ? self.new(item) : nil }.compact
      search = response.search

      { collection: collection, search: search }
    end
  end
end

app/models/maps/api/place.rb
module Maps
  class Api::Place
    include Her::Model
    use_api GOOGLE_MAP_API
    collection_path 'maps/api/place'
    RADIUS = 800
    FOOD = 'food'

    def self.search_nearby_food_places(params)
      self.get("#{collection_path}/nearbysearch/json", params)
    end

    def self.nearby_food_places(location)
      params = {
        location: location,
        radius: RADIUS,
        type: FOOD,
        key: ENV['GOOGLE_API_KEY']
      }

      response = self.search_nearby_food_places(params)
      response.results
    end
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  skip_before_action :load_current_user_data!
  skip_before_action :send_variables_to_js
  
  def create
    if params[:latitude] && params[:longitude]
      store_current_location(params[:latitude], params[:longitude])
    end

    render text: nil
  end

  def show
  end

  private
    def store_current_location(latitude, longitude)
      session[:current_latitude] = latitude
      session[:current_longitude] = longitude
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from Faraday::ConnectionFailed, with: :api_inaccessible 
  before_filter :authenticate_user!
  before_action :load_current_user_data!
  before_action :send_variables_to_js
  helper_method :sign_in_time
  
  protected
    def send_variables_to_js
      gon.clear
      gon.here = { app_id: ENV['HERE_MAP_APP_ID'], app_code: ENV['HERE_MAP_APP_CODE'] }
      gon.visitor_location = visitor_location
      gon.geo_session = { lat: session[:current_latitude], lng: session[:current_longitude] }
      gon.user_picture = @profile_small_picture
    end

    def facebook
      @facebook ||= Koala::Facebook::API.new(facebook_access_token)
    end

    def facebook_access_token
      session[:facebook_access_token]
    end

    def visitor_location
      @visitor_location ||= request.location
    end

    def api_inaccessible
      flash.now[:error] = 'Connection Lost, Please Try Again.'
      render
    end

    def sign_in_time
      DateTime.strptime(session[:sign_in_time], "%Y-%m-%d %H:%M:%S")
    end

    def load_current_user_data!
      unless session[:facebook_access_token].blank?
        @current_user ||= session[:current_user]
        @profile_small_picture ||= session[:profile_small_picture]
        @profile_big_picture ||= session[:profile_big_picture]
      end
    end

    def authenticate_user!
      redirect_to sign_in_path, turbolinks: true if session[:facebook_access_token].blank?
    end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  skip_before_filter :authenticate_user!
  layout 'dialog'

  def sign_in
    oauth = Koala::Facebook::OAuth.new(ENV['FACEBOOK_APP_ID'], ENV['FACEBOOK_APP_SECRET'], ENV['FACEBOOK_CALLBACK_URL'])
    @fb_url = oauth.url_for_oauth_code({ permissions: ENV['FACEBOOK_PERMISSIONS'] })

    if code = params[:code]
      access_token = oauth.get_access_token(code)
      store_facebook_access_token(access_token)
      retreive_current_user_data!
      return redirect_to root_path, turbolinks: true
    end

    redirect_to root_path, turbolinks: true if facebook_access_token
  end

  def sign_out
    reset_session
    redirect_to sign_in_path, turbolinks: true
  end

  private
    def store_facebook_access_token(access_token)
      reset_session
      session[:facebook_access_token] = access_token
      session[:sign_in_time] = Time.zone.now
    end

    def retreive_current_user_data!
      session[:current_user] = facebook.get_object('me', {}, api_version: ENV['FACEBOOK_API_VERSION'])
      session[:profile_small_picture] = facebook.get_picture(session[:current_user]['id'], { type: 'small'})
      session[:profile_big_picture] = facebook.get_picture(session[:current_user]['id'], { type: 'normal'})
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :current_location_present?
  def index
    # @nearest_restaurants = Maps::Api::Place.nearby_food_places("#{session[:current_latitude]},#{session[:current_longitude]}")
    @nearest_restaurants = Here::Place.search({ latitude: session[:current_latitude], longitude: session[:current_longitude], keyword: 'restaurant' })
    gon.nearest_restaurants = @nearest_restaurants.attributes
  end

  private
    def current_location_present?
      flash.now[:error] = 'Refreshing Location...' if session[:current_latitude].blank? && session[:current_longitude].blank?
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    return search_restaurants(params[:q]) if params[:q]
  end

  def show
    @location_detail = params
    gon.location_detail = @location_detail
  end

  private

    def search_restaurants(keyword)
      parameters = { latitude: '14.5576' || session[:current_latitude], longitude: '121.02' || session[:current_longitude], keyword: keyword }
      @results = Here::Place.search_with_wrap_to_model(parameters)
      gon.search_results = @results
      render
    end
end

app/helpers/api/v1/places_helper.rb
module Api::V1::PlacesHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
  def category_color_theme(category)
    categories = Here::Place::FOOD_CATEGORY

    if category == categories[0]
      'bg-red'
    elsif category == categories[1]
      'bg-aqua'
    elsif category == categories[2]
      'bg-orange'
    elsif category == categories[3]
      'bg-green'
    else
      'bg-teal'
    end
  end

  def active?(location_detail, mode)
    'active' if location_detail[:active_tab] == mode
  end

  def location_path_options(place, results)
    location = @results[:search][:context][:location]
    {
      coords: "#{place.position.first},#{place.position.second}",
      title: place.title, 
      vicinity: place.vicinity, 
      current_location: location[:address][:text],
      current_coords: "#{location[:position].first},#{location[:position].second}",
      current_lat: location[:position].first,
      current_long: location[:position].second,
      active_tab: 'public_transport_route'
    }
  end
end

app/views/authentication/sign_in.html.slim
.facebook.container
  .row
    .col-md-5.col-md-offset-7
      .sign-in-box
        .box.box-warning.disable
          .box-header
            h3.text-center Welcome to FoodPoint!
          .box-body
            .callout.callout-warning
              p Locate and route your favorite food in town with FoodPoint!
            
            .login-button
              = link_to @fb_url, title: 'Sign in with Facebook' do
                .text-center
                  = image_tag('facebook-sign-in.png', alt: 'facebook sign in logo', title: 'Sign-in with facebook')
        

app/views/authentication/sign_out.html.slim
h1 Authentication#sign_out
p Find me in app/views/authentication/sign_out.html.slim

app/views/here/places/_place.html.slim
.col-md-12
  .box.collapsed-box.box-solid class=category_color_theme(place.category[:id])
    .box-header
      .box-title
        = "#{place.title}, #{place.try(:distance)} meters away"
      .box-tools.pull-right
        button.btn.btn-box-tool data-widget='collapse'
          span.ion.ion-plus-circled.white-text
    .box-body
      = link_to location_path(place.id, location_path_options(place, @results)) do
        .info-box class=category_color_theme(place.category[:id])
          span.info-box-icon
            = image_tag(place.icon)
          .info-box-content
            .row
              / category
              .col-md-2 
                strong Category
              .col-md-9
                p = place.category[:title].gsub('/', ' ')
              / distance
              .col-md-2 
                strong Distance
              .col-md-9
                p = "#{place.try(:distance)} meters away"
              / vicinity
              .col-md-2 
                strong Vicinity
              .col-md-9
                p = raw place.try(:vicinity)

app/views/home/index.html.slim
- if session[:current_latitude] && session[:current_longitude]
  #map

app/views/layouts/application.html.slim
doctype html
html
  head
    meta name='viewport' content='initial-scale=1.0, width=device-width'
    title Foodpoint
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = Gon::Base.render_data({:init => true, :camel_case => true})
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body.skin-red class=controller_name
    .wrapper
      = render 'shared/header'
      = render 'shared/sidebar'
      .content-wrapper
        section.content-header
        section.content
          = render 'shared/flash'
          = yield
        = render 'shared/loader'
      = render 'shared/footer'
      = Gon::Base.render_data({:init => true, :camel_case => true})

app/views/layouts/dialog.html.slim
doctype html
html
  head
    title Foodpoint
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = Gon::Base.render_data({:init => true, :camel_case => true})
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body.dialog.bg-orange
    = yield
    = Gon::Base.render_data({:init => true, :camel_case => true})

app/views/locations/_search_location_form.html.slim
.row
  .col-md-12
    .input-group
      = text_field(:place, :keyword, class: 'form-control', placeholder: 'Find Nearest Restaurant, Coffee shop or Convience Store', value: params[:q])
      span.input-group-btn
        = button_tag('Search', class: 'btn bg-orange btn-lg', type: 'button', id: 'search_button')

app/views/locations/index.html.slim
= render 'search_location_form'
- unless @results.blank?
  .row.result-places
    .col-md-8
      / render restaurants
      .row
        - if @results[:collection].empty?
          .empty-results
            .callout.bg-aqua
              p
                span.ion.ion-alert
                span We Can't find the place that you're looking for.
        - else
          h4 Nearest Location:
          = render @results[:collection]
    .col-md-4
      / render current location
      .small-box.bg-red
        .inner
          h4 Your Current Location
          p = sanitize @results[:search][:context][:location][:address][:text]
        .icon
          span.ion.ion-ios-location
        .small-box-footer

app/views/locations/show.html.slim
.row
  - if @location_detail
    / locations
    .col-md-9
      .nav-tabs-custom#map-tabs
        ul.nav.nav-tabs
          li class=active?(@location_detail, 'public_transport_route')
            a href='#' data-tab='public_transport_route' data-toggle='tab' area-expanded='true'
              span.ion.ion-android-bus
              span Public Transport Route
          li class=active?(@location_detail, 'driving_route')
            a href='#' data-tab='driving_route' data-toggle='tab' area-expanded='true'
              span.ion.ion-android-car
              span Driving Route
          li class=active?(@location_detail, 'pedestrian_route')
            a href='#' data-tab='pedestrian_route' data-toggle='tab' area-expanded='true'
              span.ion.ion-android-walk
              span Pedestrian Route
        .tab-content.maps
          .tab-pane#public_transport_route class=active?(@location_detail, 'public_transport_route')
            .map-view#map_with_public_transport_route
          .tab-pane#driving_route class=active?(@location_detail, 'driving_route')
            .map-view#map_with_driving_route
          .tab-pane#pedestrian_route class=active?(@location_detail, 'pedestrian_route')
            .map-view#map_with_pedestrian_route
    / details
    .col-md-3
      / render current location
      .small-box.bg-red
        .inner
          h4 Current Location
          p = raw @location_detail[:current_location]
        .icon
          span.ion.ion-ios-location
        .small-box-footer
      / destination
      .small-box.bg-green
        .inner
          h4 Destination Location
          strong = @location_detail[:title]
          p = raw @location_detail[:vicinity]
        .icon
          span.ion.ion-ios-location
        .small-box-footer
        

app/views/shared/_flash.html.slim
- flash.delete(:timedout).each do |k, v|
  .alert.alert-dismissible class="alert-#{k}" role='alert'
    button.close type='button' data-dismiss='alert' aria-label='Close' 
      span aria-hidden='true' &times;
    = v

app/views/shared/_header.html.slim
header.main-header
  / logo
  a.logo 
    strong FoodPoint!
  nav.navbar.navbar-static-top role='navigation'
    a.sidebar-toggle data-toggle='offcanvas' role='button'
      span.ion-navicon-round
      span.sr-only Toggle Navigation
    .navbar-custom-menu
      ul.nav.navbar-nav
        - if @current_user
          li.dropdown.user.user-menu
            a.dropdown-toggle data-toggle='dropdown'
              div
                = image_tag(@profile_small_picture, class: 'user-image' )
                span = @current_user['name']
            ul.dropdown-menu
              li.user-header
                = image_tag(@profile_big_picture, class: 'image-circle')
                p = @current_user['name']
                p from #{@current_user['location']['name']}
              li.user-body
                .clearfix
                  .pull-left
                    strong Last sign in
                  .pull-right
                    p #{timeago_tag(sign_in_time, :nojs => true, :limit => 10.days.ago)}
                .clearfix
                  .pull-left
                    strong Birthday
                  .pull-right
                    p = @current_user['birthday']
                .clearfix
                  .pull-left
                    strong Gender
                  .pull-right
                    p = @current_user['gender']
                .clearfix
                  .pull-left
                    strong Email
                  .pull-right
                    p = @current_user['email']
                .clearfix
                  .pull-left
                    strong Website
                  .pull-right
                    p = @current_user['website']
                .clearfix
                  .pull-left
                    strong Verfied
                  .pull-right
                    -if @current_user['verified']
                      span.ion-ios-checkmark.bg-success
                    - else 
                      span.ion-ios-close.bg-danger
              li.user-footer
                .pull-left
                  = link_to @current_user['link'], title: 'Check facebook Profile', class: 'btn btn-default btn-flat', target: '_blank' do
                    span Facebook Profile

          li
            = link_to sign_out_path, title: 'sign out' do 
              span.ion-log-out

app/views/shared/_loader.html.slim
.loader
  .inner-loader
    p.spinner.ion-android-locate.rotate
    p Loading...

app/views/shared/_sidebar.html.slim
aside.main-sidebar
  section.sidebar
    ul.sidebar-menu
      li.header Navigation
      li.treeview
        = link_to root_path do
          span.ion.ion-ios-home
          span Home
        = link_to locations_path do 
          span.ion.ion-android-restaurant
          span Look for Restaurants
          